/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AWS */

#ifndef _Included_AWS
#define _Included_AWS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AWS
 * Method:    http_headers_new_from_blob
 * Signature: ([BI)LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_http_1headers_1new_1from_1blob
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
