/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AWS */

#ifndef _Included_AWS
#define _Included_AWS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AWS
 * Method:    awsCrtCleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtCleanUp
  (JNIEnv *, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtEventLoopGroupNew
 * Signature: (LAWS/Pointer;)LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtEventLoopGroupNew
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsNew
 * Signature: (LAWS/Pointer;)LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtCredentialsNew
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtMemBytes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_AWS_awsCrtMemBytes
  (JNIEnv *, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsProviderStaticOptionsSetSessionToken
 * Signature: (LAWS/Pointer;[BI)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtCredentialsProviderStaticOptionsSetSessionToken
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     AWS
 * Method:    awsCrtHttpHeadersToBlob
 * Signature: (LAWS/Pointer;LAWS/Pointer;)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtHttpHeadersToBlob
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtErrorStr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AWS_awsCrtErrorStr
  (JNIEnv *, jobject, jint);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsProviderStaticNew
 * Signature: (LAWS/Pointer;)LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtCredentialsProviderStaticNew
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsProviderStaticOptionsSetSecretAccessKey
 * Signature: (LAWS/Pointer;[BI)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtCredentialsProviderStaticOptionsSetSecretAccessKey
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsProviderStaticOptionsSetAccessKeyId
 * Signature: (LAWS/Pointer;[BI)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtCredentialsProviderStaticOptionsSetAccessKeyId
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsProviderStaticOptionsRelease
 * Signature: (LAWS/Pointer;)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtCredentialsProviderStaticOptionsRelease
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsOptionsSetAccessKeyId
 * Signature: (LAWS/Pointer;[BI)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtCredentialsOptionsSetAccessKeyId
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsOptionsSetSecretAccessKey
 * Signature: (LAWS/Pointer;[BI)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtCredentialsOptionsSetSecretAccessKey
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsOptionsNew
 * Signature: ()LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtCredentialsOptionsNew
  (JNIEnv *, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsOptionsRelease
 * Signature: (LAWS/Pointer;)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtCredentialsOptionsRelease
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtMemCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_AWS_awsCrtMemCount
  (JNIEnv *, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtHttpHeadersNewFromBlob
 * Signature: ([BI)LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtHttpHeadersNewFromBlob
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     AWS
 * Method:    awsCrtInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtInit
  (JNIEnv *, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtEventLoopGroupOptionsSetMaxThreads
 * Signature: (LAWS/Pointer;I)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtEventLoopGroupOptionsSetMaxThreads
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     AWS
 * Method:    awsCrtEventLoopGroupRelease
 * Signature: (LAWS/Pointer;)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtEventLoopGroupRelease
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtHttpMessageToBlob
 * Signature: (LAWS/Pointer;LAWS/Pointer;)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtHttpMessageToBlob
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtHttpMessageNewFromBlob
 * Signature: ([BI)LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtHttpMessageNewFromBlob
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     AWS
 * Method:    awsCrtDefaultAllocator
 * Signature: ()LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtDefaultAllocator
  (JNIEnv *, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtTestError
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_AWS_awsCrtTestError
  (JNIEnv *, jobject, jint);

/*
 * Class:     AWS
 * Method:    awsCrtEventLoopGroupAcquire
 * Signature: (LAWS/Pointer;)LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtEventLoopGroupAcquire
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtHttpHeadersRelease
 * Signature: (LAWS/Pointer;)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtHttpHeadersRelease
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsRelease
 * Signature: (LAWS/Pointer;)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtCredentialsRelease
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtHttpHeadersAcquire
 * Signature: (LAWS/Pointer;)LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtHttpHeadersAcquire
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsProviderStaticOptionsNew
 * Signature: ()LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtCredentialsProviderStaticOptionsNew
  (JNIEnv *, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AWS_awsCrtLastError
  (JNIEnv *, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsAcquire
 * Signature: (LAWS/Pointer;)LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtCredentialsAcquire
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsOptionsSetExpirationTimepointSeconds
 * Signature: (LAWS/Pointer;J)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtCredentialsOptionsSetExpirationTimepointSeconds
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     AWS
 * Method:    awsCrtHttpMessageRelease
 * Signature: (LAWS/Pointer;)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtHttpMessageRelease
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtMemDump
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtMemDump
  (JNIEnv *, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtEventLoopGroupOptionsNew
 * Signature: ()LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtEventLoopGroupOptionsNew
  (JNIEnv *, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtMemRelease
 * Signature: (LAWS/Pointer;)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtMemRelease
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsProviderRelease
 * Signature: (LAWS/Pointer;)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtCredentialsProviderRelease
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtErrorName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AWS_awsCrtErrorName
  (JNIEnv *, jobject, jint);

/*
 * Class:     AWS
 * Method:    awsCrtHttpMessageSetBodyStream
 * Signature: (LAWS/Pointer;LAWS/Pointer;)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtHttpMessageSetBodyStream
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtMemAcquire
 * Signature: (I)LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtMemAcquire
  (JNIEnv *, jobject, jint);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsProviderAcquire
 * Signature: (LAWS/Pointer;)LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_awsCrtCredentialsProviderAcquire
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtEventLoopGroupOptionsRelease
 * Signature: (LAWS/Pointer;)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtEventLoopGroupOptionsRelease
  (JNIEnv *, jobject, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtResetError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtResetError
  (JNIEnv *, jobject);

/*
 * Class:     AWS
 * Method:    awsCrtErrorDebugStr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AWS_awsCrtErrorDebugStr
  (JNIEnv *, jobject, jint);

/*
 * Class:     AWS
 * Method:    awsCrtCredentialsOptionsSetSessionToken
 * Signature: (LAWS/Pointer;[BI)V
 */
JNIEXPORT void JNICALL Java_AWS_awsCrtCredentialsOptionsSetSessionToken
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
