/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AWS */

#ifndef _Included_AWS
#define _Included_AWS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AWS
 * Method:    httpHeadersNewFromBlob
 * Signature: ([BI)LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_httpHeadersNewFromBlob
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
