/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AWS */

#ifndef _Included_AWS
#define _Included_AWS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AWS
 * Method:    httpHeadersNewFromBlob
 * Signature: ([BI)LAWS/Pointer;
 */
JNIEXPORT jobject JNICALL Java_AWS_httpHeadersNewFromBlob
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     AWS
 * Method:    crtInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AWS_crtInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
